config/routes.rb
Sealfriends::Application.routes.draw do

	match "pages/new" =>"pages#create", :via=>:post

	resources :introductions, :controller => :pages

    resources :pages do
  	  member do
  	    post :picture, :action => :upload
  	    get :picture
  	    get :show_picture
  	  end
      collection do
        get :search
        post :search, :action => :result
    end
  end

  devise_for :users
  
  root :to => "pages#index"

end

app/models/introduction.rb
class Introduction < ActiveRecord::Base
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
belongs_to :user

MAX_FILESIZE=500*500

  def picture_file= (p)
  @picture_file = p
  unless @picture_file.blank?
      self.picture_data = p.read
      self.content_type = p.content_type
    end
  end

def vaildate
  if @picture_file.blank?
    	errors.add(:image_file, %q|did'nt designate.| )
    elsif @image_file.content_type !~/^image/
    	errors.add(:image_file, 'is not a imege.' )
	end
end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :picture
  has_many :introductions
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :profile, :email, :password, :password_confirmation, :remember_me  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/introductions_controller.rb
class IntroductionsController < ApplicationController
  # GET /introductions
  # GET /introductions.xml
  def index
    @introductions = Introduction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @introductions }
    end
  end

  # GET /introductions/1
  # GET /introductions/1.xml
  def show
    @introduction = Introduction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @introduction }
    end
  end

  # GET /introductions/new
  # GET /introductions/new.xml
  def new
    @introduction = Introduction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @introduction }
    end
  end

  # GET /introductions/1/edit
  def edit
    @introduction = Introduction.find(params[:id])
  end

  # POST /introductions
  # POST /introductions.xml
  def create
    @introduction = Introduction.new(params[:introduction])

    respond_to do |format|
      if @introduction.save
        format.html { redirect_to(@introduction, :notice => 'Introduction was successfully created.') }
        format.xml  { render :xml => @introduction, :status => :created, :location => @introduction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @introduction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /introductions/1
  # PUT /introductions/1.xml
  def update
    @introduction = Introduction.find(params[:id])

    respond_to do |format|
      if @introduction.update_attributes(params[:introduction])
        format.html { redirect_to(@introduction, :notice => 'Introduction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @introduction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /introductions/1
  # DELETE /introductions/1.xml
  def destroy
    @introduction = Introduction.find(params[:id])
    @introduction.destroy

    respond_to do |format|
      format.html { redirect_to(introductions_url) }
      format.xml  { head :ok }
    end
  end
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
 	@current_user_name = current_user.name
 	@current_user_profile = current_user.profile
 	@picture = current_user.picture
  	@introductions = current_user.introductions
  	
  	respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @introduction }
    end

  end
  
  def show
    $user_id = User.find(params[:id]).id
  	@user_name = User.find(params[:id]).name
  	@user_profile = User.find(params[:id]).profile 
    @introduction = User.find(params[:id]).introductions

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @introduction }
    end
  end

  def new
    @introduction = Introduction.new
   #respond_to do |format|
      #format.html # new.html.erb
      #format.xml  { render :xml => @introduction }
    #end
  end
    def create
    @introduction = Introduction.new(params[:introduction])
    @introduction[:author] = current_user.id
    @introduction[:user_id] = $user_id 
    #if @introduction.save
    #redirect_to "/pages/#{$user_id}"
    respond_to do |format|
      if @introduction.save
        format.html { redirect_to :action => "/pages/#{$user_id}", :notice => 'Introduction was successfully created.' }
        format.xml  { render :xml => :introduction, :status => :created, :location => :introduction }
      else
        format.html { render :action => "pages/#{$user_id}" }
        format.xml  { render :xml => :introduction.errors, :status => :unprocessable_entity }
      end
    end
  end
  
   def upload
    if current_user.picture
       @picture = current_user.picture
    else
       @picture = Picture.new
       @picture.user_id = current_user.id
    end
@picture.content_type = params[:picture_file].content_type
@picture.picture_data = params[:picture_file].read
@picture.save
redirect_to(pages_path, :notice => 'Picture was successfully updated.')
    #respond_to do |format|
      #if @picture.update_attributes(params[:picture_file])
        #format.html { redirect_to(pages_path, :notice => 'Picture was successfully updated.') }
        #format.xml  { head :ok }
      #else
        #format.html { render :action => "picture" }
        #format.xml  { render :xml => @picture.errors, :status => :unprocessable_entity }
      #end
    #end
  end
   
  def destroy
    @introduction = Introduction.find(params[:id])
    @introduction.destroy

    respond_to do |format|
      format.html { redirect_to(pages_path) }
      format.xml  { head :ok }
    end
  end

  def search
  end
  
 def result
  @users = []
  User.all.each do |y|
  if y.name.downcase == params[:name].downcase
      @users << y
  end
  end
  render :result
  end
  
  def show_picture
    @picture = Picture.find(params[:id])
    send_data(@picture.picture_data, :type=> @picture.content_type)
  end 

 def picture
    if current_user.picture
       @picture = current_user.picture
    else
       @picture = Picture.new
       @picture.user_id = current_user.id
    end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/introductions_helper.rb
module IntroductionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/introductions/_form.html.erb
<%= form_for(@introduction) do |f| %>
  <% if @introduction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@introduction.errors.count, "error") %> prohibited this introduction from being saved:</h2>

      <ul>
      <% @introduction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/introductions/edit.html.erb
<h1>Editing introduction</h1>

<%= render 'form' %>

<%= link_to 'Show', @introduction %> |
<%= link_to 'Back', introductions_path %>

app/views/introductions/index.html.erb
<h1>Listing introductions</h1>
<table>
  <tr>
    <th>Comment</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @introductions.each do |introduction| %>
  <tr>
    <td><%= introduction.comment %></td>
    <td><%= introduction.name %></td>
    <td><%= link_to 'Show', introduction %></td>
    <td><%= link_to 'Edit', edit_introduction_path(introduction) %></td>
    <td><%= link_to 'Destroy', introduction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Introduction', new_introduction_path %>

app/views/introductions/new.html.erb
<h1>New introduction</h1>

<%= render 'form' %>

<%= link_to 'Back', introductions_path %>

app/views/introductions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @introduction.comment %>
</p>

<p>
  <b>Name:</b>
  <%= @introduction.name %>
</p>


<%= link_to 'Edit', edit_introduction_path(@introduction) %> |
<%= link_to 'Back', introductions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sealfriends</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
 <% if user_signed_in? %>
 <%= current_user.name %> / 
 <%= link_to "home", pages_path %>
 <%= link_to "find friends", search_pages_path %>
 <%= link_to "edit", edit_user_registration_path %>
  <%= link_to "logout", destroy_user_session_path, :method => 'delete' %>
 <% else %>
 <%= link_to "signin", new_user_session_path %>
 <%= link_to "signup", new_user_registration_path %>
 <% end %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <div id ="contents">
<%= yield %>
</div>
</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@introduction) do |f| %>
  <% if @introduction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@introduction.errors.count, "error") %> prohibited this introduction from being saved:</h2>

      <ul>
      <% @introduction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/index.html.erb
<h1>My Profile</h1>
<% if user_signed_in? %>
<b>Picture:</b><br/>
<% if @picture %>
<%= image_tag show_picture_page_path(@picture), :height => '64' %>
<% else %>
No Picture=>
<% end %>
<%= link_to "Change Picture", "/pages/#{current_user.id}/picture"%><br/>
<br/>
<b>Name:</b>&nbsp;&nbsp;<%= @current_user_name %><br/>
<b>Bio:</b>&nbsp;&nbsp;<%= @current_user_profile %><br/>
<% end %>
<hr>
<b>Friends Comment</b>
<table>
  <tr>
    <th>Name</th>
    <th>Link</th>
    <th>Comment</th>
    <th></th>
    <th></th>
  </tr>
<% @introductions.each do |introduction| %>
  <tr>
    <td><%= User.find(introduction.author).name %></td>
     <td><%= link_to "Page Link", "pages/#{introduction.author}" %></td>
     <td><%= introduction.comment %></td>
     <td><%= link_to 'Destroy', introduction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/pages/new.html.erb
<h1>New introduction</h1>

<%= render 'form' %>

<% #link_to 'Back', page_path %>

app/views/pages/picture.html.erb
<%= form_tag("/pages/#{current_user.id}/picture", {:multipart => true }) do  %>
<h1>New Picture</h1>
<div class="field">
    <%= label_tag :picture_file %><br />
    <%= file_field_tag :picture_file %>
</div>
 <div class="actions">
    <%= submit_tag %>
</div>
<% end %>
<%= link_to 'Back', page_path %>

app/views/pages/result.html.erb
<h1>Listing introductions</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to "Page Link", "#{user.id}" %></td>
  </tr>
<% end %>
</table>

<br />

app/views/pages/search.html.erb
<h1>Search for Friends</h1>

<%= form_tag do %>
<div class="field">
  <%= label_tag :name %>
  <%= text_field_tag :name %>
</div>

<div class="actions">
  <%= submit_tag 'Search' %>
</div>
<% end %>

app/views/pages/show.html.erb
<b>Picture</b><br/>
<%= image_tag picture_page_path(@picture), :height => '64' %><br/>
<b>Name:</b>&nbsp;&nbsp;<%= @user_name %><br/>
<b>Bio:</b>&nbsp;&nbsp;<%= @user_profile %><br/>
<hr>
<b>Friends Comment</b>&nbsp;&nbsp;<%= link_to 'New Comment', new_page_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Comment</th>
  </tr>
<% @introduction.each do |introduction| %>
  <tr>
    <td><%= User.find(introduction.author).name %></td>
    <td><%= introduction.comment %></td>
  </tr>
<% end %>
</table>